server.servlet.context-path=/gimnasio
jwt.secret=4b79d5faad3e61db0c4ece6d8449219cc0ded9bf8e04d189009520f9a4dd2d12
jwt.expiration=5000

spring.datasource.url=jdbc:mysql://localhost:3306/gimnasio?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
server.port=8081
 